baseURL = 'https://spacepakal.github.io/'
languageCode = 'en-us'
title = 'KanTuun'
theme= "nostyle"
defaultContentLanguage= "en"
[params]
  social = [
    { name = "github", url = "https://github.com/your-username" },
    { name = "twitter", url = "https://twitter.com/your-username" },
    { name = "linkedin", url = "https://linkedin.com/in/your-username" }
  ]
