baseURL = "https://spacepakal.github.io/"
languageCode = "en-us"
title = "KanTuun"
theme = "kantuun-next"
ignoreFiles = ["(^|/)\\.obsidian($|/)"]

[frontmatter]
  default = "yaml"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90
  [[menu.main]]
    identifier = "indexes"
    name = "Indexes"
    title = "Indexes"
    url = "/indexes/"
    weight = -80

[params]
  description = "Notes on learning, experiments, and technical writing."
  header_title = "Space Pakal"
  header_subtitle = "Notes on learning, experiments, and technical writing."
  mainSections = ["posts"]

[taxonomies]
  category = "categories"
  tag = "tags"
